name: Deploy iam-tool to the development stand
on: workflow_dispatch
permissions: {}
env:
  ENV_FILENAME: .env
  COMPOSE_FILENAME: compose.yml
jobs:
  build_and_push_image:
    name: Build and push image
    environment: develop
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: 'dipdeepcode/keycloak:latest'
  deploy_service:
    name: Deploy service
    needs: build_and_push_image
    environment: develop
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "KC_BOOTSTRAP_ADMIN_USERNAME=${{ secrets.KC_BOOTSTRAP_ADMIN_USERNAME }}" > ${{ env.ENV_FILENAME }}
          echo "KC_BOOTSTRAP_ADMIN_PASSWORD=${{ secrets.KC_BOOTSTRAP_ADMIN_PASSWORD }}" >> ${{ env.ENV_FILENAME }}
          echo "KC_DB_URL_HOST=${{ secrets.KC_DB_URL_HOST }}" >> ${{ env.ENV_FILENAME }}
          echo "KC_DB_URL_PORT=${{ secrets.KC_DB_URL_PORT }}" >> ${{ env.ENV_FILENAME }}
          echo "KC_DB_URL_DATABASE=${{ secrets.KC_DB_URL_DATABASE }}" >> ${{ env.ENV_FILENAME }}
          echo "KC_DB_USERNAME=${{ secrets.KC_DB_USERNAME }}" >> ${{ env.ENV_FILENAME }}
          echo "KC_DB_PASSWORD=${{ secrets.KC_DB_PASSWORD }}" >> ${{ env.ENV_FILENAME }}
          echo "APP_PORT=${{ vars.IAM_TOOL_PORT }}" >> ${{ env.ENV_FILENAME }}
      - name: Copy files via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "${{ env.ENV_FILENAME }},${{ env.COMPOSE_FILENAME }}"
          target: ${{ vars.PROJECT_DIR }}
      - name: Compose up
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ vars.PROJECT_DIR }}
            docker compose --env-file ${{ env.ENV_FILENAME }} up -d
